name: Build & Release ZIP

on:
  push:
    tags: ['v*']
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # <-- QUESTO È FONDAMENTALE

    steps:
      - uses: actions/checkout@v4
      - name: Build plugin structure
        run: |
          PLUGIN=easy-wa-contact-button
          mkdir -p dist/$PLUGIN
          rsync -a --delete \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='dist' \
            --exclude='.DS_Store' \
            --exclude='node_modules' \
            --exclude='vendor' \
            --exclude='*.zip' \
            ./ dist/$PLUGIN/
          cd dist
          zip -r ${PLUGIN}-${GITHUB_REF_NAME}.zip $PLUGIN

      - name: Attach to release (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact (manual run)
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v4
        with:
          name: plugin-zip
          path: dist/*.zip
