name: Build & Release ZIP
on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: { contents: write }
    env: { PLUGIN: chat2book-button }
    steps:
      - uses: actions/checkout@v4
      - name: Build plugin zip
        run: |
          mkdir -p dist/$PLUGIN
          rsync -a --delete --exclude='.git' --exclude='.github' --exclude='dist' \
            --exclude='.DS_Store' --exclude='node_modules' --exclude='vendor' --exclude='*.zip' \
            ./ dist/$PLUGIN/
          cd dist && zip -r ${PLUGIN}-${GITHUB_REF_NAME}.zip $PLUGIN
      - name: Create/Update release + upload asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
