name: Build & Release ZIP

on:
  push:
    tags: ['v*']      # es. v1.0.1
  workflow_dispatch:  # avvio manuale (utile per test)

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write        # necessario per creare la release

    env:
      PLUGIN: easy-wa-contact-button

    steps:
      - uses: actions/checkout@v4

      - name: Build plugin zip
        run: |
          mkdir -p dist/$PLUGIN
          rsync -a --delete \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='dist' \
            --exclude='.DS_Store' \
            --exclude='node_modules' \
            --exclude='vendor' \
            --exclude='*.zip' \
            ./ dist/$PLUGIN/
          cd dist
          zip -r ${PLUGIN}-${GITHUB_REF_NAME}.zip $PLUGIN

      # CREA la release (non la aggiorna)
      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}      # es. v1.0.1
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false

      # CARICA lo zip come asset della release appena creata
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/${{ env.PLUGIN }}-${{ github.ref_name }}.zip
          asset_name: ${{ env.PLUGIN }}-${{ github.ref_name }}.zip
          asset_content_type: application/zip
